/**
 * GENERATED by scripts/write-build-fingerprint.mjs — do not edit; the build
 * overwrites this file on every `pnpm build`. The committed stub (all nulls)
 * keeps source-mode compilation and CI (test-before-build) working on a fresh
 * checkout; a null id means "unknown", which isInstanceStale treats as not stale.
 */
import type { BuildFingerprint } from './fingerprint.ts'

/** The build-time identity of THIS compiled code (decision 7). */
export const BUILD_FINGERPRINT: BuildFingerprint = {
  id: "e6d1b03d9aa6cf24",
  buildTime: "2026-08-23T13:38:42.868Z",
  gitCommit: null,
}
